config/routes.rb
Rails.application.routes.draw do
 
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root to: 'events#index'

  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
  resources :attended_events
  resources :creators  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User", foreign_key: "attendee_id"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :attended_events
    has_many :attendees, through: :attended_events
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :events, foreign_key: :creator_id
    has_many :attended_events, foreign_key: :attendee_id

    def upcoming_events
        self.events.where("date > ? ", Time.now)
    end
    
    def previous_events
        self.events.where("date < ? ", Time.now)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params) if logged_in?
        if @event.save 
            flash[:success] = "Event created!"
            redirect_to current_user
        else 
            render 'new'   
        end      
    end

    def index 
        @events = Event.all.order(created_at: :desc)
        @past_events = Event.where("date < ? ", Time.now)
        @future_events = Event.where("date > ? ", Time.now)
    end
    
    
    

    private 

    def event_params
        params.require(:event).permit(:title, :details)
    end
    
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user 
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          # Handle a successful save.
          log_in @user
          flash[:success] = "Signup Successful"
          redirect_to @user
        else
          render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
        @events = @user.events
        @upcoming_events = @user.upcoming_events
        @previous_events = @user.previous_events
    end


    private

    def user_params
      params.require(:user).permit(:username, :password,
                                   :password_confirmation)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
      end

      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
      end

      def logged_in?
        !current_user.nil?
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event-box-<%= event.id %>">
  <li id="event-<%= event.id %>">
    <h4>
      <%= link_to event.title, event_path(event.id) %>
    </h4>
    <strong>
      <%= link_to event.creator.username, event.creator %>
    </strong>


    <p class="event-details">
      <%= event.details %>
    </p>
    
    <p>
      <%= event.date %>
    </p>


    <span class="timestamp">
      Posted <%= time_ago_in_words(event.created_at) %> ago.
    </span>
  </li>
</div>

app/views/events/index.html.erb
<div class="strongbox">
  <h1>Future Events</h1>
  <ol class="future-events">
            <%= render @future_events %>
  </ol>
</div>
<hr>
<div class="longbox">
  <h1>Past Events</h1>
  <ol class="events">
            <%= render @past_events %>
  </ol>
</div>

app/views/events/new.html.erb
<div class="event-form center">
      <%= form_for(@event) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title %>
      
            <%= f.label :details %>
            <%= f.text_area :details %>
      
            <%= f.label :date %>
            <%= f.date_field  :date %>
            <br>
            <%= f.submit "Create event", class: "btn btn-primary" %>
      <% end %>
</div>

app/views/events/show.html.erb
<h1>
     <%= link_to @event.creator.username, user_path %> 
    <%= @event.title %>
    <%= @event.details %>
    
</h1>

<% unless @event.attendees.blank? %>
<h2>Users Attending</h2>
<% @event.attendees.each do |attendee| %>
<h3><%= attendee.username%></h3>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PrivateEvents</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<nav>
  <div class="navBar" id="mainNavBar">
    <% if logged_in? %>
    <a href="#">logged in <%= link_to "#{@current_user.username}", current_user %></a>
    <% else %>
    <a href=""><%= link_to 'Sign in', login_path %></a>
    <% end %>
    <a href="#"><%= link_to 'Home', root_path %></a>
  </div>
</nav>

<body>
  <div class="container">
    <%= yield %>
  </div>

</body>

</html>

app/views/users/_attended_event.html.erb
<li id="event-<%= event.id %>">
  <%= link_to event.creator.username, event.creator %>
 <%= link_to event.title, event_path(event.id) %>
 <br>
 <%= event.details %>
 <br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(event.created_at) %> ago.
  </span>
</li>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="row">


  <div class="one-third column">&nbsp;</div>
  <div class="one-third column">
    <h1><%= @user.username %> <% if @user.events.any? %> events (<%= @user.events.count %>)</h1>
    <% end %>
  </div>
  <div class="one-third column">&nbsp;</div>
</div>

<% if @user.events.any? %>

<div class="strongbox">

  <h3>Future Events</h3>

  <ol class="future-events">
    <%= render @upcoming_events %>
  </ol>

</div>

<hr>

<div class="longbox">

  <h3>Past Events</h3>

  <ol class="events">
    <%= render @previous_events %>
  </ol>

</div>

<% end %>

<!-- Stolen from Javier -->
<!-- Used in rework before adding to Odin Project -->
<% unless  @user.attended_events.blank? %>
<h3><%= @user.username %> attended events</h3>
<% @user.events.each do |events| %>
<h3><%= events.title %></h3>
<% end %>
<% end %>